
insert into ricetta (id, nome, url_Image, descrizione) values(nextval('ricetta_seq'), 'Carbonara', 'Espaguetis_carbonara.jpg', 'La Carbonara, iconico piatto italiano, è una pasta cremosa e succulenta arricchita con uova, guanciale o pancetta croccante, pecorino romano e pepe nero. La sua salsa vellutata si ottiene mescolando uova crude con formaggio e pepe, creando una deliziosa armonia di sapori. Servita su spaghetti o rigatoni al dente, questa prelibatezza culinaria è un ode alla tradizione romana, offrendo un esperienza culinaria irresistibile e ricca di gusto.');
insert into ricetta (id, nome, url_Image, descrizione) values(nextval('ricetta_seq'), 'Amatriciana', 'amatriciana.png', 'Un classico piatto italiano, l amatriciana è un condimento per la pasta composto da guanciale, pomodoro, pecorino romano e peperoncino. Il guanciale viene saltato in padella con olio d oliva e peperoncino per creare un sapore ricco e speziato, mentre il pomodoro aggiunge dolcezza e acidità al piatto. Il tutto viene poi amalgamato con abbondante pecorino romano per ottenere una salsa cremosa e gustosa. Servita con pasta rigata, l amatriciana è un esplosione di sapori tradizionali romani.');
insert into ricetta (id, nome, url_Image, descrizione) values(nextval('ricetta_seq'), 'Cacio e Pepe', 'cacio_e_pepe.png', 'Un piatto semplice ma delizioso, la cacio e pepe è una pasta romana che mette in evidenza la bellezza dei sapori semplici. Preparata con solo tre ingredienti principali - pecorino romano, pepe nero e pasta - questa pietanza è un esempio classico della cucina italiana. Il pecorino romano viene fuso con un po  d acqua di cottura della pasta per creare una salsa cremosa e saporita, mentre il pepe nero aggiunge un tocco di calore e spezie. Servita con pasta spaghetto o tonnarelli, la cacio e pepe è un esperienza culinaria genuina e appagante.');

insert into cuoco (id, nome, cognome, url_Image, nascita) values(nextval('cuoco_seq'), 'Bruno', 'Barbieri', 'BrunoBarbieri.png','1958-08-25');
insert into cuoco (id, nome, cognome, url_Image, nascita) values(nextval('cuoco_seq'), 'Antonino', 'Cannavacciuolo', 'Antonino-Cannavacciuolo.png','1990-10-13');
insert into cuoco (id, nome, cognome, url_Image, nascita) values(nextval('cuoco_seq'), 'Massimiliano', 'Mariola', 'max_mariola.png','1969-04-11');
insert into cuoco (id, nome, cognome, url_Image, nascita) values(nextval('cuoco_seq'), 'Giorgio', 'Barchiesi', 'giorgione.png','1957-06-07');

insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Uova', 'Un alimento altamente nutriente e versatile, l uovo è una fonte di proteine di alta qualità. È comunemente usato nella cucina per preparare piatti dolci e salati, come torte, frittate, e salse', 'uova.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Guanciale', 'Un tipo di pancetta italiana che viene preparata utilizzando il grasso e la carne della guancia del maiale. Ha un sapore intenso e aromatico ed è spesso utilizzato come ingrediente principale nella famosa pasta all amatriciana e in altre ricette della cucina italiana', 'guanciale.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Pecorino', 'Il Pecorino Romano è un formaggio italiano stagionato, a pasta dura e dal sapore robusto e salato. Viene grattugiato su piatti come la pasta cacio e pepe o la pasta alla carbonara per aggiungere gusto e complessità', 'pecorino.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Spaghetti', 'Un alimento base della cucina italiana, la pasta è costituita principalmente da farina di grano e acqua. Può essere accompagnata da una vasta gamma di salse e condimenti', 'spaghetti.png');

insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Vino Bianco', 'Un vino ottenuto dalla fermentazione di uve bianche. Viene spesso utilizzato nella cucina italiana per aggiungere profondità e complessità ai piatti. Il vino bianco è un ingrediente comune in salse, stufati e marinature, e può anche essere servito come accompagnamento ai pasti', 'vino_bianco.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Pomodori Pelati', 'Pomodori privati della buccia, che vengono immersi in acqua bollente per renderne più semplice la rimozione. Questi pomodori sono pronti per essere utilizzati nella preparazione di salse, sughi e altri piatti che richiedono pomodori senza buccia', 'pelati.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Peperoncino Fresco', 'Una varietà di peperoncino piccante, il peperoncino fresco aggiunge un tocco di calore e sapore ai piatti. Viene spesso utilizzato nella cucina italiana e in molte altre cucine del mondo per aggiungere un po di vivacità e pizzico a piatti come pasta, carne e salse', 'peperoncino.png');
insert into ingrediente (id, nome, descrizione, url_Image) values(nextval('ingrediente_seq'), 'Pepe Nero', 'Una spezia comunemente usata ottenuta dalla macinazione dei semi essiccati del pepe nero. Aggiunge un sapore pungente e leggermente piccante ai piatti e viene utilizzato sia durante la cottura che come condimento finale', 'Pepe-nero.png');

 